import { Router } from 'express';

const router = Router();

// Enhanced schema definitions for import field mapping
// This defines the available fields for each entity type for import/export
const getEntitySchema = (entityType: string) => {
  const schemas = {
    employees: {
      fields: [
        {
          name: 'empId',
          displayName: 'Employee ID',
          description: 'Unique employee identifier',
          dataType: 'text',
          required: false,
          autoGenerated: true,
          example: 'EMP-00001'
        },
        {
          name: 'englishName',
          displayName: 'English Name',
          description: 'Employee full name in English',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'John Smith'
        },
        {
          name: 'arabicName',
          displayName: 'Arabic Name',
          description: 'Employee full name in Arabic',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'جون سميث'
        },
        {
          name: 'department',
          displayName: 'Department',
          description: 'Employee department',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'IT'
        },
        {
          name: 'title',
          displayName: 'Job Title',
          description: 'Employee job position',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'Software Engineer'
        },
        {
          name: 'employmentType',
          displayName: 'Employment Type',
          description: 'Type of employment',
          dataType: 'enum',
          required: true,
          autoGenerated: false,
          enumValues: ['Full-time', 'Part-time', 'Contract', 'Intern', 'Freelance'],
          example: 'Full-time'
        },
        {
          name: 'joiningDate',
          displayName: 'Joining Date',
          description: 'Date when employee joined',
          dataType: 'date',
          required: true,
          autoGenerated: false,
          example: '2024-01-15'
        },
        {
          name: 'exitDate',
          displayName: 'Exit Date',
          description: 'Date when employee left (if applicable)',
          dataType: 'date',
          required: false,
          autoGenerated: false,
          example: '2024-12-31'
        },
        {
          name: 'personalEmail',
          displayName: 'Personal Email',
          description: 'Employee personal email address',
          dataType: 'email',
          required: false,
          autoGenerated: false,
          example: 'john.smith@gmail.com'
        },
        {
          name: 'corporateEmail',
          displayName: 'Corporate Email',
          description: 'Employee work email address',
          dataType: 'email',
          required: false,
          autoGenerated: false,
          example: 'john.smith@company.com'
        },
        {
          name: 'personalMobile',
          displayName: 'Personal Mobile',
          description: 'Employee personal phone number',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: '+1234567890'
        },
        {
          name: 'workMobile',
          displayName: 'Work Mobile',
          description: 'Employee work phone number',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: '+1234567891'
        },
        {
          name: 'idNumber',
          displayName: 'ID Number',
          description: 'National ID or identification number',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: '1234567890'
        },
        {
          name: 'directManager',
          displayName: 'Direct Manager ID',
          description: 'Employee ID of direct manager',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '5'
        },
        {
          name: 'status',
          displayName: 'Employment Status',
          description: 'Current employment status',
          dataType: 'enum',
          required: false,
          autoGenerated: false,
          enumValues: ['Active', 'Resigned', 'Terminated', 'On Leave'],
          example: 'Active'
        }
      ]
    },

    assets: {
      fields: [
        {
          name: 'assetId',
          displayName: 'Asset ID',
          description: 'Unique asset identifier',
          dataType: 'text',
          required: false,
          autoGenerated: true,
          example: 'AST-00001'
        },
        {
          name: 'type',
          displayName: 'Asset Type',
          description: 'Type/category of the asset',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'Laptop'
        },
        {
          name: 'brand',
          displayName: 'Brand',
          description: 'Asset brand/manufacturer',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'Dell'
        },
        {
          name: 'modelNumber',
          displayName: 'Model Number',
          description: 'Manufacturer model number',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'XPS-13-9370'
        },
        {
          name: 'modelName',
          displayName: 'Model Name',
          description: 'Commercial model name',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'XPS 13'
        },
        {
          name: 'serialNumber',
          displayName: 'Serial Number',
          description: 'Unique serial number',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'SN123456789'
        },
        {
          name: 'specs',
          displayName: 'Specifications',
          description: 'General asset specifications',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'Intel i7, 16GB RAM, 512GB SSD'
        },
        {
          name: 'cpu',
          displayName: 'CPU',
          description: 'Processor specification',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'Intel Core i7-8550U'
        },
        {
          name: 'ram',
          displayName: 'RAM',
          description: 'Memory specification',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: '16GB DDR4'
        },
        {
          name: 'storage',
          displayName: 'Storage',
          description: 'Storage specification',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: '512GB NVMe SSD'
        },
        {
          name: 'status',
          displayName: 'Status',
          description: 'Current asset status',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'Available'
        },
        {
          name: 'purchaseDate',
          displayName: 'Purchase Date',
          description: 'Date when asset was purchased',
          dataType: 'date',
          required: false,
          autoGenerated: false,
          example: '2024-01-15'
        },
        {
          name: 'buyPrice',
          displayName: 'Purchase Price',
          description: 'Asset purchase cost',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '1200.00'
        },
        {
          name: 'warrantyExpiryDate',
          displayName: 'Warranty Expiry',
          description: 'Warranty expiration date',
          dataType: 'date',
          required: false,
          autoGenerated: false,
          example: '2027-01-15'
        },
        {
          name: 'lifeSpan',
          displayName: 'Life Span',
          description: 'Expected life span in years',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '5'
        },
        {
          name: 'outOfBoxOs',
          displayName: 'Operating System',
          description: 'Default operating system',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'Windows 11 Pro'
        },
        {
          name: 'assignedEmployeeId',
          displayName: 'Assigned Employee ID',
          description: 'ID of assigned employee',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '123'
        }
      ]
    },
    
    tickets: {
      fields: [
        {
          name: 'ticketId',
          displayName: 'Ticket ID',
          description: 'Unique ticket identifier',
          dataType: 'text',
          required: false,
          autoGenerated: true,
          example: 'TKT-00001'
        },
        {
          name: 'title',
          displayName: 'Title',
          description: 'Brief description of the issue',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'Laptop not starting'
        },
        {
          name: 'description',
          displayName: 'Description',
          description: 'Detailed description of the issue',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'The laptop shows a black screen when powered on'
        },
        {
          name: 'type',
          displayName: 'Type',
          description: 'Nature of the request',
          dataType: 'enum',
          required: true,
          autoGenerated: false,
          enumValues: ['Incident', 'Service Request', 'Problem', 'Change'],
          example: 'Incident'
        },
        {
          name: 'category',
          displayName: 'Category',
          description: 'Issue category',
          dataType: 'text',
          required: true,
          autoGenerated: false,
          example: 'Hardware'
        },
        {
          name: 'urgency',
          displayName: 'Urgency',
          description: 'How quickly the issue needs to be addressed',
          dataType: 'enum',
          required: true,
          autoGenerated: false,
          enumValues: ['Low', 'Medium', 'High', 'Critical'],
          example: 'Medium'
        },
        {
          name: 'impact',
          displayName: 'Impact',
          description: 'Business impact level',
          dataType: 'enum',
          required: true,
          autoGenerated: false,
          enumValues: ['Low', 'Medium', 'High', 'Critical'],
          example: 'Medium'
        },
        {
          name: 'priority',
          displayName: 'Priority',
          description: 'Calculated priority level (from urgency × impact)',
          dataType: 'enum',
          required: false,
          autoGenerated: true,
          enumValues: ['Low', 'Medium', 'High', 'Critical'],
          example: 'Medium'
        },
        {
          name: 'status',
          displayName: 'Status',
          description: 'Current ticket status',
          dataType: 'enum',
          required: false,
          autoGenerated: false,
          enumValues: ['Open', 'In Progress', 'Resolved', 'Closed'],
          example: 'Open'
        },
        {
          name: 'submittedById',
          displayName: 'Submitted By ID',
          description: 'Employee ID who submitted the ticket',
          dataType: 'number',
          required: true,
          autoGenerated: false,
          example: '123'
        },
        {
          name: 'assignedToId',
          displayName: 'Assigned To ID',
          description: 'User ID assigned to handle the ticket',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '456'
        },
        {
          name: 'relatedAssetId',
          displayName: 'Related Asset ID',
          description: 'Asset ID related to this ticket',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '789'
        },
        {
          name: 'timeSpent',
          displayName: 'Time Spent',
          description: 'Time spent on the ticket in minutes',
          dataType: 'number',
          required: false,
          autoGenerated: false,
          example: '120'
        },
        {
          name: 'dueDate',
          displayName: 'Due Date',
          description: 'Expected resolution date',
          dataType: 'date',
          required: false,
          autoGenerated: false,
          example: '2024-02-15'
        },
        {
          name: 'slaTarget',
          displayName: 'SLA Target',
          description: 'Service level agreement target date',
          dataType: 'date',
          required: false,
          autoGenerated: false,
          example: '2024-02-14T10:00:00Z'
        },
        {
          name: 'completionTime',
          displayName: 'Completion Time',
          description: 'When the ticket was completed',
          dataType: 'date',
          required: false,
          autoGenerated: true,
          example: '2024-02-13T14:30:00Z'
        },
        {
          name: 'resolution',
          displayName: 'Resolution',
          description: 'How the issue was resolved',
          dataType: 'text',
          required: false,
          autoGenerated: false,
          example: 'Replaced faulty power adapter'
        }
      ]
    }
  };
  
  return schemas[entityType as keyof typeof schemas] || null;
};

// Get database schema for entity type
router.get('/schema/:entityType', (req, res) => {
  try {
    const { entityType } = req.params;
    const schema = getEntitySchema(entityType);
    
    if (!schema) {
      return res.status(400).json({ error: 'Invalid entity type' });
    }
    
    res.json(schema);
  } catch (error) {
    console.error('Schema fetch error:', error);
    res.status(500).json({ error: 'Failed to fetch schema' });
  }
});

export default router;