version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: simpleit-postgres
    restart: always
    environment:
      POSTGRES_USER: simpleituser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-simpleit_secure_password}
      POSTGRES_DB: simpleit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simpleituser -d simpleit"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SimpleIT application
  app:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    container_name: simpleit-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://simpleituser:${DB_PASSWORD:-simpleit_secure_password}@postgres:5432/simpleit
      SESSION_SECRET: ${SESSION_SECRET:-simpleit_session_secret}
      REPLIT_DOMAINS: localhost
      ISSUER_URL: http://localhost
      REPL_ID: simpleit-production
      USE_HTTPS: "false"
    ports:
      - "80:5000"
    volumes:
      - ./uploads:/app/uploads

  # Nginx for SSL termination and reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: simpleit-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  postgres_data: